# Generated by Django 3.2.5 on 2021-09-02 05:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='video')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_video', to='posts.post')),
            ],
        ),
    ]
